<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap-std/options.proto

namespace Fproto_wrap;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fproto_wrap.FProtoWrapOptions</code>
 */
class FProtoWrapOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool wrap = 1;</code>
     */
    private $wrap = false;

    public function __construct() {
        \GPBMetadata\GithubCom\RangelReale\FprotoWrapStd\Options::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool wrap = 1;</code>
     * @return bool
     */
    public function getWrap()
    {
        return $this->wrap;
    }

    /**
     * Generated from protobuf field <code>bool wrap = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setWrap($var)
    {
        GPBUtil::checkBool($var);
        $this->wrap = $var;

        return $this;
    }

}

