<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap-std/sqltag.proto

namespace Fproto_wrap;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fproto_wrap.SQLTag</code>
 */
class SQLTag extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool tag_disable = 1;</code>
     */
    private $tag_disable = false;
    /**
     * Generated from protobuf field <code>string tag_fieldname = 2;</code>
     */
    private $tag_fieldname = '';

    public function __construct() {
        \GPBMetadata\GithubCom\RangelReale\FprotoWrapStd\Sqltag::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool tag_disable = 1;</code>
     * @return bool
     */
    public function getTagDisable()
    {
        return $this->tag_disable;
    }

    /**
     * Generated from protobuf field <code>bool tag_disable = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setTagDisable($var)
    {
        GPBUtil::checkBool($var);
        $this->tag_disable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tag_fieldname = 2;</code>
     * @return string
     */
    public function getTagFieldname()
    {
        return $this->tag_fieldname;
    }

    /**
     * Generated from protobuf field <code>string tag_fieldname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTagFieldname($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag_fieldname = $var;

        return $this;
    }

}

