<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap-headers/headers.proto

namespace Fproto_wrap_headers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fproto_wrap_headers.Headers</code>
 */
class Headers extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .fproto_wrap_headers.Headers.Values> headers = 1;</code>
     */
    private $headers;

    public function __construct() {
        \GPBMetadata\GithubCom\RangelReale\FprotoWrapHeaders\Headers::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>map<string, .fproto_wrap_headers.Headers.Values> headers = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Generated from protobuf field <code>map<string, .fproto_wrap_headers.Headers.Values> headers = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fproto_wrap_headers\Headers_Values::class);
        $this->headers = $arr;

        return $this;
    }

}

