<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap-headers/headers.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrapHeaders;

class Headers
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acb020a386769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702d686561646572732f686561646572732e70726f74" .
            "6f12136670726f746f5f777261705f6865616465727322b4010a07486561" .
            "64657273123a0a076865616465727318012003280b32292e6670726f746f" .
            "5f777261705f686561646572732e486561646572732e4865616465727345" .
            "6e7472791a180a0656616c756573120e0a0676616c756573180120032809" .
            "1a530a0c48656164657273456e747279120b0a036b657918012001280912" .
            "320a0576616c756518022001280b32232e6670726f746f5f777261705f68" .
            "6561646572732e486561646572732e56616c7565733a023801423b5a3967" .
            "69746875622e636f6d2f52616e67656c5265616c652f6670726f746f2d77" .
            "7261702d686561646572732f676f777261702f677770726f746f62067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

