<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap-std/jsontag.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrapStd;

class Jsontag
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0add010a346769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702d7374642f6a736f6e7461672e70726f746f120b66" .
            "70726f746f5f777261701a20676f6f676c652f70726f746f6275662f6465" .
            "7363726970746f722e70726f746f22350a074a534f4e54616712130a0b74" .
            "61675f64697361626c6518012001280812150a0d7461675f6669656c646e" .
            "616d6518022001280942375a356769746875622e636f6d2f52616e67656c" .
            "5265616c652f6670726f746f2d777261702d7374642f676f777261702f67" .
            "7770726f746f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

