<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap-std/jsonobject.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrapStd;

class Jsonobject
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4010a376769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702d7374642f6a736f6e6f626a6563742e70726f746f" .
            "120b6670726f746f5f77726170221b0a0a4a534f4e4f626a656374120d0a" .
            "0576616c756518012001280942375a356769746875622e636f6d2f52616e" .
            "67656c5265616c652f6670726f746f2d777261702d7374642f676f777261" .
            "702f677770726f746f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

