<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap-std/options.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrapStd;

class Options
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac9010a346769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702d7374642f6f7074696f6e732e70726f746f120b66" .
            "70726f746f5f777261701a20676f6f676c652f70726f746f6275662f6465" .
            "7363726970746f722e70726f746f22210a114650726f746f577261704f70" .
            "74696f6e73120c0a047772617018012001280842375a356769746875622e" .
            "636f6d2f52616e67656c5265616c652f6670726f746f2d777261702d7374" .
            "642f676f777261702f677770726f746f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

