<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap-std/uuid.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrapStd;

class Uuid
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac2010a316769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702d7374642f757569642e70726f746f120b6670726f" .
            "746f5f7772617022150a0455554944120d0a0576616c7565180120012809" .
            "22280a084e756c6c55554944120d0a0576616c7565180120012809120d0a" .
            "0576616c696418022001280842375a356769746875622e636f6d2f52616e" .
            "67656c5265616c652f6670726f746f2d777261702d7374642f676f777261" .
            "702f677770726f746f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

