<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap/jsonobject.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrap;

class Jsonobject
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a336769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702f6a736f6e6f626a6563742e70726f746f120b6670" .
            "726f746f5f77726170221b0a0a4a534f4e4f626a656374120d0a0576616c" .
            "756518012001280942335a316769746875622e636f6d2f52616e67656c52" .
            "65616c652f6670726f746f2d777261702f676f777261702f677770726f74" .
            "6f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

