<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap/jsontag.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrap;

class Jsontag
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad5010a306769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702f6a736f6e7461672e70726f746f120b6670726f74" .
            "6f5f777261701a20676f6f676c652f70726f746f6275662f646573637269" .
            "70746f722e70726f746f22350a074a534f4e54616712130a0b7461675f64" .
            "697361626c6518012001280812150a0d7461675f6669656c646e616d6518" .
            "022001280942335a316769746875622e636f6d2f52616e67656c5265616c" .
            "652f6670726f746f2d777261702f676f777261702f677770726f746f6206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

