<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap/options.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrap;

class Options
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac1010a306769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702f6f7074696f6e732e70726f746f120b6670726f74" .
            "6f5f777261701a20676f6f676c652f70726f746f6275662f646573637269" .
            "70746f722e70726f746f22210a114650726f746f577261704f7074696f6e" .
            "73120c0a047772617018012001280842335a316769746875622e636f6d2f" .
            "52616e67656c5265616c652f6670726f746f2d777261702f676f77726170" .
            "2f677770726f746f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

