<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap/sqltag.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrap;

class Sqltag
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad3010a2f6769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702f73716c7461672e70726f746f120b6670726f746f" .
            "5f777261701a20676f6f676c652f70726f746f6275662f64657363726970" .
            "746f722e70726f746f22340a0653514c54616712130a0b7461675f646973" .
            "61626c6518012001280812150a0d7461675f6669656c646e616d65180220" .
            "01280942335a316769746875622e636f6d2f52616e67656c5265616c652f" .
            "6670726f746f2d777261702f676f777261702f677770726f746f62067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

