<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap/time.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrap;

class Time
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abf010a2d6769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702f74696d652e70726f746f120b6670726f746f5f77" .
            "72617022440a084e756c6c54696d6512290a0576616c756518012001280b" .
            "321a2e676f6f676c652e70726f746f6275662e54696d657374616d70120d" .
            "0a0576616c696418022001280842335a316769746875622e636f6d2f5261" .
            "6e67656c5265616c652f6670726f746f2d777261702f676f777261702f67" .
            "7770726f746f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

