<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap/uuid.proto

namespace GPBMetadata\GithubCom\RangelReale\FprotoWrap;

class Uuid
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aba010a2d6769746875622e636f6d2f52616e67656c5265616c652f6670" .
            "726f746f2d777261702f757569642e70726f746f120b6670726f746f5f77" .
            "72617022150a0455554944120d0a0576616c756518012001280922280a08" .
            "4e756c6c55554944120d0a0576616c7565180120012809120d0a0576616c" .
            "696418022001280842335a316769746875622e636f6d2f52616e67656c52" .
            "65616c652f6670726f746f2d777261702f676f777261702f677770726f74" .
            "6f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

