<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap-validator-std/validator.proto

namespace Validator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>validator.OneOfFieldValidator</code>
 */
class OneOfFieldValidator extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether the field is required.
     *
     * Generated from protobuf field <code>bool required = 1;</code>
     */
    private $required = false;

    public function __construct() {
        \GPBMetadata\GithubCom\RangelReale\FprotoWrapValidatorStd\Validator::initOnce();
        parent::__construct();
    }

    /**
     * Whether the field is required.
     *
     * Generated from protobuf field <code>bool required = 1;</code>
     * @return bool
     */
    public function getRequired()
    {
        return $this->required;
    }

    /**
     * Whether the field is required.
     *
     * Generated from protobuf field <code>bool required = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->required = $var;

        return $this;
    }

}

