<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/RangelReale/fproto-wrap-validator-std/validator.proto

namespace Validator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>validator.RepeatedFieldValidator</code>
 */
class RepeatedFieldValidator extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether the field is required.
     *
     * Generated from protobuf field <code>bool required = 1;</code>
     */
    private $required = false;
    /**
     * Field value of length greater than this value.
     *
     * Generated from protobuf field <code>int64 length_gt = 12;</code>
     */
    private $length_gt = 0;
    /**
     * Field value of length smaller than this value.
     *
     * Generated from protobuf field <code>int64 length_lt = 13;</code>
     */
    private $length_lt = 0;
    /**
     * Field value of length greater than this value.
     *
     * Generated from protobuf field <code>int64 length_gte = 14;</code>
     */
    private $length_gte = 0;
    /**
     * Field value of length smaller than this value.
     *
     * Generated from protobuf field <code>int64 length_lte = 15;</code>
     */
    private $length_lte = 0;
    /**
     * Field value of integer strictly equal this value.
     *
     * Generated from protobuf field <code>int64 length_eq = 16;</code>
     */
    private $length_eq = 0;

    public function __construct() {
        \GPBMetadata\GithubCom\RangelReale\FprotoWrapValidatorStd\Validator::initOnce();
        parent::__construct();
    }

    /**
     * Whether the field is required.
     *
     * Generated from protobuf field <code>bool required = 1;</code>
     * @return bool
     */
    public function getRequired()
    {
        return $this->required;
    }

    /**
     * Whether the field is required.
     *
     * Generated from protobuf field <code>bool required = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->required = $var;

        return $this;
    }

    /**
     * Field value of length greater than this value.
     *
     * Generated from protobuf field <code>int64 length_gt = 12;</code>
     * @return int|string
     */
    public function getLengthGt()
    {
        return $this->length_gt;
    }

    /**
     * Field value of length greater than this value.
     *
     * Generated from protobuf field <code>int64 length_gt = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLengthGt($var)
    {
        GPBUtil::checkInt64($var);
        $this->length_gt = $var;

        return $this;
    }

    /**
     * Field value of length smaller than this value.
     *
     * Generated from protobuf field <code>int64 length_lt = 13;</code>
     * @return int|string
     */
    public function getLengthLt()
    {
        return $this->length_lt;
    }

    /**
     * Field value of length smaller than this value.
     *
     * Generated from protobuf field <code>int64 length_lt = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLengthLt($var)
    {
        GPBUtil::checkInt64($var);
        $this->length_lt = $var;

        return $this;
    }

    /**
     * Field value of length greater than this value.
     *
     * Generated from protobuf field <code>int64 length_gte = 14;</code>
     * @return int|string
     */
    public function getLengthGte()
    {
        return $this->length_gte;
    }

    /**
     * Field value of length greater than this value.
     *
     * Generated from protobuf field <code>int64 length_gte = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLengthGte($var)
    {
        GPBUtil::checkInt64($var);
        $this->length_gte = $var;

        return $this;
    }

    /**
     * Field value of length smaller than this value.
     *
     * Generated from protobuf field <code>int64 length_lte = 15;</code>
     * @return int|string
     */
    public function getLengthLte()
    {
        return $this->length_lte;
    }

    /**
     * Field value of length smaller than this value.
     *
     * Generated from protobuf field <code>int64 length_lte = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLengthLte($var)
    {
        GPBUtil::checkInt64($var);
        $this->length_lte = $var;

        return $this;
    }

    /**
     * Field value of integer strictly equal this value.
     *
     * Generated from protobuf field <code>int64 length_eq = 16;</code>
     * @return int|string
     */
    public function getLengthEq()
    {
        return $this->length_eq;
    }

    /**
     * Field value of integer strictly equal this value.
     *
     * Generated from protobuf field <code>int64 length_eq = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLengthEq($var)
    {
        GPBUtil::checkInt64($var);
        $this->length_eq = $var;

        return $this;
    }

}

